# Generated by Django 5.2.8 on 2025-12-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giving_to', to='users.participant')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_from', to='users.participant')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
