<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-11-30 11:07
=======
# Generated by Django 5.2.8 on 2025-11-30 00:23
>>>>>>> origin/dev

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giving_match', to='users.player')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_match', to='users.player')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'constraints': [models.UniqueConstraint(fields=('giver',), name='unique_giver'), models.UniqueConstraint(fields=('recipient',), name='unique_recipient')],
            },
=======
                ('giver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giving_to', to='users.participant')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_from', to='users.participant')),
            ],
>>>>>>> origin/dev
        ),
    ]
