# Generated by Django 5.2.8 on 2025-12-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gifts.wishlistitem')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_gifts', to='matches.match')),
            ],
            options={
                'verbose_name_plural': 'Gift Assignments',
                'unique_together': {('match', 'gift')},
            },
        ),
    ]
