# Generated by Django 5.2.8 on 2025-12-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_giftassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giftassignment',
            unique_together=set(),
        ),
    ]
