<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-11-30 11:07

=======
# Generated by Django 5.2.8 on 2025-11-30 00:23

import django.db.models.deletion
from django.conf import settings
>>>>>>> origin/dev
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/dev
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Player',
            fields=[
                ('user_id', models.CharField(help_text='unique identifier assigned by the organizer for pairing purposes.', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text="The participant's display name.", max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/dev
            ],
        ),
    ]
