import random
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from .models import Match
from users.models import Participant


@login_required
def matches_list(request):
    """Show the current user's Secret Santa match."""
    try:
        participant = Participant.objects.get(user=request.user)
    except Participant.DoesNotExist:
        messages.error(
            request,
            'You need to be a participant to view matches. Join Secret Santa first!'
        )
        return render(request, "matches/matches_list.html", {'match': None})

    # Get the match where this participant is the giver
    try:
        match = Match.objects.get(giver=participant)
        has_match = True
    except Match.DoesNotExist:
        match = None
        has_match = False
        messages.info(
            request,
            'No match found yet. Matches will be generated by the administrator.'
        )

    context = {
        "match": match,
        "has_match": has_match,
    }

    return render(request, "matches/matches_list.html", context)


def generate_matches():
    """
    Randomly match each participant with another participant.
    Each person gives to a randomly assigned person (circular matching).

    Returns: (success: bool, message: str)
    """
    # Get all participants
    participants = list(Participant.objects.all())

    # Need at least 2 people
    if len(participants) < 2:
        return False, "Need at least 2 participants to create matches!"

    # Check if matches already exist
    if Match.objects.exists():
        return False, "Matches already exist! Clear them first."

    try:
        with transaction.atomic():
            # Shuffle participants randomly
            random.shuffle(participants)

            # Create circular random matches
            # Each person gives to the next person in the shuffled list
            # Last person gives to first person (ensures everyone is matched)
            for i in range(len(participants)):
                giver = participants[i]
                receiver = participants[(i + 1) % len(participants)]
                Match.objects.create(giver=giver, receiver=receiver)

            count = len(participants)
            return True, f"Successfully matched {count} participants!"

    except Exception as e:
        return False, f"Error: {str(e)}"
